-- AlterTable
ALTER TABLE "shipments" ADD COLUMN     "customs_billing_date" DATE,
ADD COLUMN     "customs_billing_value" DOUBLE PRECISION,
ADD COLUMN     "customs_document_url" TEXT,
ADD COLUMN     "customs_payment_date" DATE,
ADD COLUMN     "customs_payment_status" TEXT NOT NULL DEFAULT 'BELUM DIBAYAR',
ADD COLUMN     "forwarder_billing_value" DOUBLE PRECISION,
ADD COLUMN     "forwarder_doc_date" DATE,
ADD COLUMN     "forwarder_doc_status" TEXT NOT NULL DEFAULT 'BELUM ADA INVOICE',
ADD COLUMN     "forwarder_document_url" TEXT,
ADD COLUMN     "forwarder_invoice_date" DATE,
ADD COLUMN     "forwarder_invoice_number" TEXT,
ADD COLUMN     "forwarder_payment_date" DATE,
ADD COLUMN     "forwarder_payment_status" TEXT NOT NULL DEFAULT 'BELUM DIBAYAR',
ADD COLUMN     "nopen" TEXT,
ADD COLUMN     "notul" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notul_notes" TEXT,
ADD COLUMN     "pib" TEXT,
ADD COLUMN     "pib_date" DATE;
